### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Vorror** [FranzSkuffka/vue-medium-editor#17]
How do we configure the various Medium Editor options?

**Comment by janwirth** [comment]
Currently, configuration is not supported.

If it's urgent take a look at https://github.com/gcoda/vue-medium-editor and https://github.com/FranzSkuffka/vue-medium-editor/pull/16

If you can wait another week I recommend you to wait for this repo's implementation. I have a specific concept in mind already.

**Comment by pizzot** [comment]
Hi @FranzSkuffka 

Just a heads up we're looking forward to the ability to configure the editor, particulary the mode option.

Thanks

**Comment by janwirth** [comment]
@okneloper @Vorror I would appreciate your thoughts, but TL;DR: I will go with gcoda's solution for now.

Hey, you are not forgotten, I have been putting some though into this and I guess that passing it as props similarly to (@gcoda's solution)[https://github.com/FranzSkuffka/vue-medium-editor/tree/curried-config] makes sense because it allows you to easily configure the plugin.

However this approach would modify all the instances of the components so I was thinking about using the function approach where I would pass the option to a function returning the configured object. This allows us to have multiple instances live at the same time with different configurations:
https://github.com/FranzSkuffka/vue-medium-editor/pull/16/commits/1a87891d2d36c65c1e57629af49ad84728ca295e

There's a little playground over here where I am trying out different approaches:
https://github.com/FranzSkuffka/vue-medium-editor/tree/playground

So what needs to be done?
1. rewrite plugin so that it allows multiple instances to peacefully coexist.
2. Test whether they do not share scope / trigger the same event and cause some kind of side effect
3. Write documentation
4. Update Website

So the API that I think would make sense is as follows:
```
// editorConfigurationView.vue
import editor from 'vue-medium-editor'
const lightEditor = editor('light')
const advancedEditor = editor('advanced')


<light-editor :config='lightConfig'> 
<advanced-editor :config='advancedConfig'> 

// edit.vue
const lightEditor = editor('light')
const advancedEditor = editor('advanced')

<template v-if='editMode == "simple">
     <light-editor> 
</template>
<template v-if='editMode == "simple">
      <advanced-editor> 
</template>
```
The editors would register within the vue root instance using the string they were passed to.
Like this you can require whichever version you need in any vue component, configure it there and re-use it in any other component.

I wonder whether this is also possible using only props in the manner of
```
// editorConfigurationView.vue
<vue-medium-editor type='advanced' :config='lightConfig'>
<vue-medium-editor type='advanced' :config='advancedConfig'>
// edit.vue
<vue-medium-editor type='editMode'>
```
I just wonder whether the props would then be updated automatically in all those instances.

**Comment by pizzot** [comment]
Thanks. I looked at the playground and it makes sense how you see it working. I think though it would make sense to leave the option to pass the settings in a prop and use the component out of the box (as it is in the current version), they way @gcoda did it. This would simplify usage for cases when you just need 1 editor or when there's too many different types of them. Also can the custom tag option still be specified with the new approach?

**Comment by janwirth** [comment]
I will use gcoda's approach and extend it.

Custom elements will of course still be supported!

**Comment by janwirth** [comment]
Sorry guys, been really busy in the recent days.

I've got this on my todo list.
