### ISSUE TITLE
Add support for data attributes.

### ISSUE THREAD

**Issue by wousser** [FranzSkuffka/vue-medium-editor#36]
The data-placeholder attr gets overwritten by options
`<medium-editor custom-tag='h2' data-placeholder='Your name' :text='name' :options='options' v-on:edit='applyTextEdit'>`

`const options = {
  placeholder: {
    hideOnClick: false
  }
}`

Expected outcome: Placeholder text = 'Your name'
Actual outcome: Placeholder text = 'Type your text' // the editor standard text.

Version:
vue2-medium-editor@1.0.4 
  └── medium-editor@5.23.0

**Comment by janwirth** [comment]
The `data`-attribs for vue-medium-editor are not supported. Please use the `option` prop for everything.

For configuring the placeholder, please refer to:
https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#placeholder-options

**Comment by janwirth** [comment]
Please let me know if you need any additional support for a specific use case :)

**Comment by wousser** [comment]
I see. Thanks. Using option prop is a possible, but that means a new instance for each editor. Are you considering adding support for data-attributes in the future?

**Comment by janwirth** [comment]
I get your point. To implement this, we need a `prop` named `dataAttributes` or something in order to then use the render function to add those attributes to the element before MediumEditor processes it. 

For now, I will reopen it. It is on the bottom of the TODO list though until the demand increases. First I need to put some time into release 1.1.0.

PR is welcome though.

**Comment by janwirth** [comment]
With #46 we are generating a new instance for each component. Also, I want to keep the code as simple as possible while data-attributes do not seem to be a convention in the VueJS community.

I will close this now and re-open for discussion when there is more demand.
